---
title: "Day 5"
author: "Derek Sollberger"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library("tidyverse")
sf_crime_data <- readxl::read_xlsx("sf_crime.xlsx")
n <- nrow(sf_crime_data)
```

```{r}
sf_crime_data
```


```{r}
sf_crime_data |>
  ggplot() +
  geom_segment(aes(x = year, y = prop_crime_rate,
                   xend = year[n], yend = prop_crime_rate[n],
                   color = slope),
               size = 2) +
  geom_point(aes(x = year, y = prop_crime_rate, color = slope), size = 6) +
  scale_color_continuous(low = "blue", high = "red") +
  #scale_x_discrete(breaks = 2014:2022,
  #                 labels = stringr::str_split(toString(2014:2022), ", ")) +
  labs(title = "Property Crime in San Francisco",
       subtitle = "30 Day Chart Challenge, Day 5: Slopes",
       caption = "Data Source: sfgov.org, Uniform Crime Reporting\n(intentionally bad graph)",
       x = "Year",
       y = "Property Crimes per Week") +
  theme(#axis.text.x = element_blank(),
        #axis.text.y = element_blank(),
        #axis.ticks = element_blank(),
        legend.position = "bottom",
        panel.background = element_rect(fill = alpha("antiquewhite2", 0.5)),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        plot.subtitle = element_text(color = "blue", hjust = 0.5, size = 10),
        plot.title = element_text(color = "red", hjust = 0.5, size = 15))
```

