---
title: "Day 8"
author: "Derek Sollberger"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---

```{r setup, message = FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = TRUE)
library("ggridges")
library("terra")
library("tidyverse")

# Earth digital elevation raster layer
# https://www.ngdc.noaa.gov/mgg/global/global.html
d8_data_raw <- terra::rast("world_DEM.tif")
```

```{r}
# https://www.patrickbaylis.com/blog/2021-03-13-downsampling-magic/
d8_data_downsampled <- terra::aggregate(d8_data_raw, fact = 10)
d8_data_df <- as.data.frame(d8_data_downsampled, xy = TRUE)
colnames(d8_data_df) <- c("long", "lat", "elevation")
```

```{r}
ca_data_df <- d8_data_df |>
  filter(long > -125) |>
  filter(long < -114) |>
  filter(lat > 32) |>
  filter(lat < 42) |>
  mutate(long_round = round(long,1), #round to nearest 0.1
         lat_round = ceiling(lat*2)/2) |> #round to nearest 0.5
  group_by(long_round, lat_round) |>
  mutate(avg_elevation = mean(elevation, na.rm = TRUE)) |>
  ungroup()
```

```{r}
ca_data_df |>
  filter(elevation > 0) |>
  ggplot(aes(x = long, y = lat_round, 
             height = avg_elevation, group = lat_round)) +
  # https://cran.r-project.org/web/packages/ggridges/vignettes/introduction.html
  ggridges::geom_density_ridges(color = "black",
                                fill = "#964b00", 
                                rel_min_height=0.001,
                                scale = 1.5,
                                stat = "identity") +
  labs(title = "Elevation Map of California and Nevada",
       subtitle = "30 Day Chart Challenge, Day 8: Mountains",
       caption = "Data Source: NOAA",
       x = "longitude", 
       y = "latitude") +
  theme(axis.text.x = element_text(size = 10),
        axis.text.y = element_text(size = 10),
        axis.ticks = element_blank(),
        axis.title.x = element_text(size = 15),
        axis.title.y = element_text(size = 15),
        legend.position = "bottom",
        # https://www.sessions.edu/color-calculator/
        panel.background = element_rect(fill = "#009696"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        plot.subtitle = element_text(color = "#4b0096", 
                                     hjust = 0.5, 
                                     size = 15),
        plot.title = element_text(color = "#964b00",
                                  hjust = 0.5,
                                  size = 20))
```
