---
title: "Day 2"
author: "Derek Sollberger"
date: "4/01/2022"
output: html_document
---

```{r setup, include=FALSE, message = FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = TRUE)
library("ggimage")
library("ggrepel")
library("tidyverse")
```

```{r}
df <- data.frame(
  name = c("Adam Duvall","Max Fried","Jacob Stallings","Brandon Crawford","Harrison Bader","Tommy Edman","Tyler O’Neill","Paul Goldschmidt","Nolan Arenado"),
  team = c("ATL","ATL","PIT","SFG","STL","STL","STL","STL","STL"),
  y = c(1,2,1,1,2,1,3,4,5),
  logo = c("mlblogos/atlanta-braves-logo.png",
           "mlblogos/atlanta-braves-logo.png",
           "mlblogos/pittsburgh-pirates-logo.png",
           "mlblogos/san-francisco-giants-logo.png",
           "mlblogos/st-louis-cardinals-logo.png",
           "mlblogos/st-louis-cardinals-logo.png",
           "mlblogos/st-louis-cardinals-logo.png",
           "mlblogos/st-louis-cardinals-logo.png",
           "mlblogos/st-louis-cardinals-logo.png")
)
```

```{r}
df |>
  ggplot(aes(x = team, y = y, label = name)) +
  ggrepel::geom_label_repel(aes(x = team, y = y),
                            nudge_x = 0.00,
                            nudge_y = -0.5) +
  ggimage::geom_image(aes(x = team, y = y, image = logo),
                      size = 0.1,
                      by = "width",
                      asp = 1.618) +
  # ylim(0,6) +
  scale_x_discrete(labels = c("ATL", "PIT", "SFG", "STL", "")) +
  scale_y_discrete(breaks = 1:5,
                   limits = 1:5,
                   labels = c("1", "2", "3", "4", "5")) +
  labs(title = "National League Gold Glove Winners (2021 Season)",
       subtitle = "30 Day Chart Challenge, Day 2: Pictogram",
       caption = "Data Source: SABR.org",
       x = "Team",
       y = "number of players") +
  theme(#axis.text.x = element_blank(),
        #axis.text.y = element_blank(),
        #axis.ticks = element_blank(),
        legend.position = "none",
        # legend.title = element_blank(),
        panel.background = element_blank(),
        panel.grid.minor = element_blank(),
        plot.subtitle = element_text(color = "red", hjust = 0.5, size = 20),
        plot.title = element_text(color = "blue", hjust = 0.5, size = 25))
```

