---
title: "Day 6"
author: "Derek Sollberger"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library("tidyverse")

# https://ourworldindata.org/grapher/share-countries-where-homosexuality-is-legal?country=~OWID_WRL
d6_data_raw <- readr::read_csv("share-countries-where-homosexuality-is-legal.csv")
colnames(d6_data_raw) <- c("location", "source", "year", "legal", "illegal")
```

```{r}
d6_data <- d6_data_raw |>
  select(3:5) |>
  pivot_longer(cols = !year,
               names_to = "legality",
               values_to = "num_countries")
d6_data$legality <- factor(d6_data$legality,
                           levels = c("legal", "illegal"))
```


```{r}
head(d6_data)
```

```{r}
str(d6_data)
```

```{r}
d6_data |>
  filter(year >= 1969) |>
  ggplot() +
  geom_bar(aes(x = year, y = num_countries, 
               fill = legality, group = legality), stat = "identity")
```
```{r}
# https://www.statology.org/population-pyramid-in-r/
d6_data |>
  filter(year >= 1969) |>
  ggplot() +
  geom_bar(aes(x = year,
               y = ifelse(legality == "legal", num_countries, -num_countries),
               fill = legality,
               group = legality),
           color = "gray50",
           stat = "identity") +
  labs(title = "Legality of Homosexuality",
       subtitle = "30 Day Chart Challenge, Day 6: OWID",
       caption = "Data Source: Our World in Data",
       x = "Year", 
       y = "Number of Countries") +
  scale_fill_manual(values = c("#8C4799", "#ADAD23")) +
  scale_y_continuous(labels = abs,
                     limits = max(d6_data$num_countries) * c(-1,1)) +
  theme(#axis.text.x = element_blank(),
        #axis.text.y = element_blank(),
        #axis.ticks = element_blank(),
        legend.position = "right",
        panel.background = element_rect(fill = alpha("#23ADAD", 0.5)),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        plot.subtitle = element_text(color = "blue", hjust = 0.5, size = 15),
        plot.title = element_text(color = "red", hjust = 0.5, size = 20))
```

```{r}
d6_data |>
  filter(year >= 1969) |>
  ggplot() +
  geom_bar(aes(x = year,
               y = ifelse(legality == "legal", num_countries, -num_countries),
               fill = legality,
               group = legality),
           color = "gray50",
           stat = "identity") +
  labs(title = "Legality of Homosexuality",
       subtitle = "30 Day Chart Challenge, Day 6: OWID",
       caption = "Data Source: Our World in Data",
       x = "Year", 
       y = "Number of Countries") +
  scale_fill_manual(values = c("#8C4799", "#ADAD23")) +
  scale_y_continuous(labels = abs,
                     limits = max(d6_data$num_countries) * c(-1,1)) +
  theme(#axis.text.x = element_blank(),
        #axis.text.y = element_blank(),
        #axis.ticks = element_blank(),
        legend.position = "right",
        panel.background = element_rect(fill = alpha("#23ADAD", 0.5)),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        plot.subtitle = element_text(color = "black", 
                                     hjust = 0.9, 
                                     #margin = margin(t = 60, b = -20),
                                     size = 15,
                                     vjust = -100),
        plot.title = element_text(color = "black",
                                  hjust = 0.10,
                                  # margin = margin(t = 10, b = -60),
                                  size = 20,
                                  vjust = -25))
```



