---
title: "Day 12"
author: "Derek"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---

```{r setup, message = FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = TRUE)
library("ggrepel")
library("ggthemes")
library("tidyverse")
```

```{r, message = FALSE, warning = FALSE}
# https://www.kaggle.com/datasets/neelgajare/2022-usa-college-rankings-more
d12_data <- readr::read_csv("colleges.csv")

# fix column names
colnames(d12_data) <- c("index", "institution", "tuition", "enrollment")

# rankings started at zero??
d12_data <- d12_data |>
  mutate(ranking = index + 1,
         forLabel = rep(FALSE, nrow(d12_data)))
```

```{r}
#prepare for geom_label

# label my university: Merced
d12_data$forLabel[stringr::str_detect(d12_data$institution, "Merced")] <- TRUE

# ranked highest
#d12_data$forLabel[which.min(d12_data$ranking)] <- TRUE

# highest tuition?
#d12_data$forLabel[which.max(d12_data$tuition)] <- TRUE
# lowest tuition?
#d12_data$forLabel[which.min(d12_data$tuition)] <- TRUE

# highest enrollment?
#d12_data$forLabel[which.max(d12_data$enrollment)] <- TRUE
# lowest enrollment?
#d12_data$forLabel[which.min(d12_data$enrollment)] <- TRUE

d12_data_for_labels <- d12_data |>
  filter(forLabel)
```


```{r}
logo_path <- "ucm_seal_fullcolor_2019.png"
logo_path <- "UCM_Bobcat.png"
# https://design-system.economist.com/documents/CHARTstyleguide_20170505.pdf

d12_data |>
  ggplot(aes(x = ranking, y = tuition)) +
  geom_point(color = "#00588D") +
  geom_label_repel(aes(x = ranking, y = tuition,
                       label = "University of California Merced"),
                   data = d12_data_for_labels,
                   fill = "#EBB434",
                   # nudge_x = 100,
                   nudge_y = -33000,
                   # point.padding = NA,
                   segment.color = "#EBB434",
                   segment.size = 2,
                   arrow = arrow(ends = "last",
                                 length = unit(0.03, "npc"),
                                 type = "closed")) +
  ggimage::geom_image(aes(x = ranking, y = tuition, 
                          image = logo_path),
                      data = d12_data_for_labels,
                      size = 0.05,
                      by = "width",
                      asp = 1.618) +
  ggimage::geom_image(aes(x = 350, y = 57500, 
                          image = logo_path),
                      data = d12_data_for_labels,
                      size = 0.2,
                      by = "width",
                      asp = 1.618) +
  labs(title = "UC Merced Entered the Top 100",
       subtitle = "30 Day Chart Challenge, Day 12: Emulating The Economist",
       x = "US News Ranking (2022)",
       y = "Out-of-State Tuition (US dollars)",
       caption = "Source: Kaggle, Neel Gajare") +
  ggthemes::theme_economist() +
  theme(panel.grid.major = element_line(color = "#B7C6CF"),
        plot.caption = element_text(hjust = 0.0))
```

