---
title: "Day 15"
author: "Derek Sollberger"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---

```{r setup, message = FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = TRUE)
library("ggradar")
library("patchwork")
library("tidyverse")
```

```{r, message = FALSE, warning = FALSE}
# https://www.reddit.com/r/comicbooks/comments/g925r3/marvel_official_power_grid_ratings_sortable_sheet/
d15_data_raw <- readxl::read_xlsx("Marvel Powergrid Ratings.xlsx")

# make copy
d15_data <- d15_data_raw |>
  janitor::clean_names() |>
  rename(fighting = fighting_skills,
         energy = energy_projection)
```

```{r}
# call on the Fantastic Four!
# there were several superheroes and super-villians with some similar names
# so it was faster to code the search with their real names
d15_data <- d15_data |>
  filter(stringr::str_detect(real_name, "Richards, Reed") | 
           stringr::str_detect(real_name, "Storm-Richards, Susan") |
           stringr::str_detect(real_name, "Storm, Jonathon") |
           stringr::str_detect(real_name, "Grimm, Benjamin"))

# focus on columns with hero names and stats
d15_data <- d15_data |>
  select(1, 6:11)

# ensure numeric columns
# d15_data <- d15_data |> mutate_if(is.numeric, as.numeric)
d15_data$intelligence <- as.numeric(d15_data$intelligence)
d15_data$strength     <- as.numeric(d15_data$strength)
d15_data$speed        <- as.numeric(d15_data$speed)
d15_data$durability   <- as.numeric(d15_data$durability)
d15_data$energy       <- as.numeric(d15_data$energy)
d15_data$fighting     <- as.numeric(d15_data$fighting)
```

```{r}
# prepare for radar chart (AKA spider graph) by indicating max and min values
# extremes_mat <- matrix(c(rep(7, 6), rep(0, 6)), nrow = 2, ncol = 6)
extremes_mat <- matrix(rep(0, 12), nrow = 2, ncol = 6)
extremes_mat[1,] <- 7
extremes_df  <- data.frame(extremes_mat)
extremes_df$character <- c("Max", "Min")
extremes_df <- extremes_df |>
  select(7, 1:6)
colnames(extremes_df) <- colnames(d15_data)


# row bind
d15_df <- rbind(extremes_df, d15_data)
```

```{r}
# https://www.datanovia.com/en/blog/beautiful-radar-chart-in-r-using-fmsb-and-ggplot-packages/
ggradar(d15_data,
        grid.min = 0, grid.mid = 3, grid.max = 7,
        # Polygons
        group.line.width = 1, 
        group.point.size = 3,
        group.colours = c("orange", "red", "blue", "brown"),
        # Background and grid lines
        background.circle.colour = "white",
        gridline.mid.colour = "grey",
        legend.position = "bottom")
```

```{r}
# Thing
p1 <- d15_data |>
  filter(character == "Thing") |>
  ggradar(grid.min = 0, grid.mid = 3, grid.max = 7,
          # Polygons
          group.line.width = 2, 
          group.point.size = 7,
          group.colours = c("brown"),
          # Background and grid lines
          background.circle.colour = "white",
          gridline.mid.colour = "grey",
          legend.position = "bottom") +
  labs(title = "Thing",
       subtitle = "Ben Grimm") +
  theme(plot.subtitle = element_text(color = "brown", hjust = 0.5, size = 20),
        plot.title = element_text(color = "brown", hjust = 0.5, size = 25))

# Mr Fantastic
p2 <- d15_data |>
  filter(character == "Mister Fantastic") |>
  ggradar(grid.min = 0, grid.mid = 3, grid.max = 7,
          # Polygons
          group.line.width = 2, 
          group.point.size = 7,
          group.colours = c("blue"),
          # Background and grid lines
          background.circle.colour = "white",
          gridline.mid.colour = "grey",
          legend.position = "bottom") +
  labs(title = "Mr Fantastic",
       subtitle = "Reed Richards") +
  theme(plot.subtitle = element_text(color = "blue", hjust = 0.5, size = 20),
        plot.title = element_text(color = "blue", hjust = 0.5, size = 25))

# Invisible Woman
p3 <- d15_data |>
  filter(character == "Invisible Woman") |>
  ggradar(grid.min = 0, grid.mid = 3, grid.max = 7,
          # Polygons
          group.line.width = 2, 
          group.point.size = 7,
          group.colours = c("red"),
          # Background and grid lines
          background.circle.colour = "white",
          gridline.mid.colour = "grey",
          legend.position = "bottom") +
  labs(title = "Invisible Woman",
       subtitle = "Sue Storm-Richards") +
  theme(plot.subtitle = element_text(color = "red", hjust = 0.5, size = 20),
        plot.title = element_text(color = "red", hjust = 0.5, size = 25))

# Human Torch
p4 <- d15_data |>
  filter(character == "Human Torch") |>
  ggradar(grid.min = 0, grid.mid = 3, grid.max = 7,
          # Polygons
          group.line.width = 2, 
          group.point.size = 7,
          group.colours = c("orange"),
          # Background and grid lines
          background.circle.colour = "white",
          gridline.mid.colour = "grey",
          legend.position = "bottom") +
  labs(title = "Human Torch",
       subtitle = "Johnny Storm") +
  theme(plot.subtitle = element_text(color = "orange", hjust = 0.5, size = 20),
        plot.title = element_text(color = "orange", hjust = 0.5, size = 25))
```

```{r}
# patchwork
p1 + p2 + p3 + p4
# didn't place in one row?!?!
```

```{r}
# going to save individually
ggsave("day15_1.png", plot = p1, device = "png",
       width = 1500, height = 1500, units = "px")
ggsave("day15_2.png", plot = p2, device = "png",
       width = 1500, height = 1500, units = "px")
ggsave("day15_3.png", plot = p3, device = "png",
       width = 1500, height = 1500, units = "px")
ggsave("day15_4.png", plot = p4, device = "png",
       width = 1500, height = 1500, units = "px")
```

