---
title: "Day 10"
author: "Derek Sollberger"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---

```{r setup, message = FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = TRUE)
library("tidyverse")
N <- 1000 #number of trials
n_vals <- seq(5, 50, 5) #sample sizes
m <- length(n_vals)
df <- data.frame(
  sample_size = n_vals,
  prop_significant = rep(NA, m)
)
```

```{r}
ggplot() +
  xlim(0, 20) +
  geom_function(fun = dexp, 
                args = list(rate = 1/10),
                color = "red", size = 3) +
  geom_function(fun = dexp, 
                args = list(rate = 1/15),
                color = "blue", size = 3) +
  labs(title = "Exponential Distributions",
       subtitle = "mean = 10",
       caption = "mean = 15",
       x = "", 
       y = "") +
  theme(#axis.text.x = element_blank(),
        #axis.text.y = element_blank(),
        axis.ticks = element_blank(),
        #axis.title.x = element_text(size = 15),
        #axis.title.y = element_text(size = 15),
        #legend.position = "bottom",
        panel.background = element_rect(fill = "white"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        plot.caption = element_text(color = "blue", 
                                     hjust = 0.5, 
                                     size = 15),
        plot.subtitle = element_text(color = "red", 
                                     hjust = 0.5, 
                                     size = 15),
        plot.title = element_text(color = "black",
                                  hjust = 0.5,
                                  size = 20))
```

```{r}
for(i in 1:m){
  significance_tracker <- rep(NA, N)
  for(j in 1:N){
    A <- rexp(n_vals[i], 1/10)
    B <- rexp(n_vals[i], 1/15)
    significance_tracker[j] <- t.test(A,B)$p.value < 0.05
  }
  df$prop_significant <- mean(significance_tracker)
}
```

