---
title: "Day 16"
author: "Derek Sollberger"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---

```{r setup, message = FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = TRUE)
library("tidyverse")
```

```{r}
d16_data_raw <- readxl::read_xlsx("chesapeake_bay_program_data_student.xlsx")
```

```{r}
d16_data <- d16_data_raw |>
  select(temp_bottom, salinity_bottom, DO_bottom) |>
  mutate(hypoxia_bool = ifelse(DO_bottom < 2, "hypoxic", "healthy"))
```

```{r}
d16_data |>
  ggplot(aes(x = temp_bottom, y = salinity_bottom)) +
  geom_point(aes(color = hypoxia_bool),
             alpha = 0.5,
             size = 5) +
  scale_color_manual(name = "Oxygen Concentration",
                     values = c("darkgreen", "red")) +
  labs(title = "Chesapeake Bay Hypoxia Studies",
       subtitle = "30 Day Chart Challenge, Day 16: Environment",
       caption = "Data Source: Chesapeake Bay Program",
       x = "temperature (Celsius)",
       y = "salinity (ppt)") +
  theme(#axis.text.x = element_blank(),
        #axis.text.y = element_blank(),
        #axis.ticks = element_blank(),
        legend.position = "bottom",
        legend.title = element_text(color = "red"),
        panel.background = element_blank(),
        panel.grid.minor = element_blank(),
        plot.caption = element_text(color = "darkgreen", hjust = 0.5, size = 15),
        plot.subtitle = element_text(color = "darkgreen", hjust = 0.5, size = 20),
        plot.title = element_text(color = "red", hjust = 0.5, size = 25))
```

