---
title: "Day 21"
author: "Derek Sollberger"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---

```{r setup, message = FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = TRUE)
library("tidyverse")
```

```{r, message = FALSE, warning = FALSE}
# https://www.census.gov/data/tables/time-series/demo/popest/2010s-total-cities-and-towns.html
d21_data_raw <- readxl::read_xlsx("SUB-IP-EST2019-ANNRNK.xlsx", skip = 3)

```

```{r}
d21_data <- d21_data_raw |>
  janitor::clean_names() |>
  rename(city = x2) |>
  filter(!is.na(city)) #further avoids headers and footers

d21_data$census <- as.numeric(d21_data$census)

d21_data <- d21_data |>
  filter(!is.na(census)) |>
  filter(!is.na(x2019)) |>
  mutate(percent_change = 100*(x2019 - census) / census) |>
  mutate(city_label = paste0(round(percent_change, 2), "%, ",
                             stringr::str_replace(city, " city", ""))) |>
  # indicate top 5 and bottom 5 changes
  mutate(city_bool = (percent_change %in%
           head(percent_change[order(percent_change)], 5)) |
           (percent_change %in%
           tail(percent_change[order(percent_change)], 5)))

d21_data_long <- d21_data |>
  pivot_longer(cols = starts_with("x20"),
               names_to = "x_year",
               values_to = "population") |>
  mutate(year = stringr::str_replace(x_year, "x", "")) |>
  mutate(start_dot = 0)

d21_data_up <- d21_data_long |>
  filter(city_bool & year == 2019 & percent_change > 0)
d21_data_down <- d21_data_long |>
  filter(city_bool & year == 2019 & percent_change < 0)
```

```{r}
d21_plot <- d21_data_long |>
  ggplot() +
  geom_segment(aes(x = 2010, xend = 2019,
                   y = start_dot, yend = percent_change,
                   group = city),
               color = "gray50") +
  
  geom_segment(aes(x = 2010, xend = 2019,
                   y = start_dot, yend = percent_change,
                   group = city),
               color = "darkgreen",
               data = d21_data_up,
               size = 3) +
  ggrepel::geom_label_repel(aes(x = 2019, y = percent_change,
                                label = city_label),
                            data = d21_data_up,
                            nudge_x = 4) +
  
  geom_segment(aes(x = 2010, xend = 2019,
                   y = start_dot, yend = percent_change,
                   group = city),
               color = "red",
               data = d21_data_down,
               size = 2) +
  ggrepel::geom_label_repel(aes(x = 2019, y = percent_change,
                                label = city_label),
                            data = d21_data_down,
                            nudge_x = 4) +
  
  xlim(2010, 2025) +
  ylim(-10, 150) +
  labs(title = "Population Change in US Cities",
       subtitle = "30 Day Chart Challenge\nDay 21: Downward or Upward",
       caption = "Population Percent Change from year 2010 to 2019\nCities that had over 50,000 people in year 2010\nData Source: Census.gov",
       x = "",
       y = "") +
  theme(axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks = element_blank(),
        legend.position = "none",
        legend.title = element_blank(),
        panel.background = element_rect(fill = "white"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        plot.title = element_text(color = "darkgreen", 
                                  size = 25,
                                  vjust = -20),
        plot.subtitle = element_text(color = "darkgreen",
                                     size = 20,
                                     vjust = -30),
        plot.caption = element_text(color = "red",
                                     size = 15,
                                    hjust = 0.0,
                                    vjust = 10))
```

