---
title: "Day 27"
author: "Derek Sollberger"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---

```{r setup, message = FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = TRUE)
library("tidyverse")
```

```{r, message = FALSE, warning = FALSE}
# https://en.wikipedia.org/wiki/List_of_solar_storms
d27_data_raw <- readr::read_csv("Carrington.csv")
n <- nrow(d27_data_raw)
```

```{r}
# data wrangling
# splitter <- rep(TRUE, n)
# splitter[seq(2,n,2)] <- FALSE #make every other entry 'FALSE'
d27_data <- d27_data_raw |>
  filter(!stringr::str_detect(description, "geomagnetic")) |>
  mutate(index = 1:n(),
         label_text = paste0(year, ": ", description))

# d27_data_down <- d27_data |> filter(splitter)
# d27_data_up <- d27_data |> filter(!splitter)
```

```{r}
d27_plot <- d27_data |>
  ggplot(aes(x = 0, y = -index)) +
  geom_line(color = "orange", size = 5) +
  
  # I ended up not liking how I would need to do extra work
  # to get ggrepel to work
  # ggrepel::geom_label_repel(aes(x = year, y = 0, 
  #                               label = label_text),
  #                           color = "white",
  #                           data = d27_data_down,
  #                           fill = "darkblue",
  #                           nudge_y = -3) +
  # ggrepel::geom_label_repel(aes(x = year, y = 0, 
  #                               label = label_text),
  #                           color = "white",
  #                           data = d27_data_up,
  #                           fill = "darkblue",
  #                           nudge_y = 3) +
  
  ggtext::geom_textbox(aes(x = 0, y = -index, label = label_text),
                       color = "white",
                       data = d27_data,
                       fill = "darkblue",
                       # hjust = -1,
                       # width = 3,
                       orientation = "upright") +
  labs(title = "When is the Next\nCarrington Event?",
       subtitle = "Coronal mass ejections and solar flares\ncan knock out electronics worldwide",
       caption = "30 Day Chart Challenge, Day 27: Future?",
       x = "",
       y = "") +
  theme(axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks = element_blank(),
        legend.position = "none",
        legend.title = element_blank(),
        panel.background = element_rect(fill = "black"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        plot.background = element_rect(fill = "black"),
        plot.title = element_text(size = 25, face = "bold",
                                  color = "orange", hjust = 0.5),
        plot.subtitle = element_text(size = 20,
                                  color = "orange", hjust = 0.5),
        plot.caption = element_text(size = 15,
                                  color = "orange", hjust = 0.5))
```

