---
title: "Day 26"
author: "Derek Sollberger"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: html_document
---

```{r setup, message = FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = TRUE)
library("ggfittext")
library("tidyverse")
```

```{r, message = FALSE, warning = FALSE}
# https://web.northeastern.edu/seigen/11Magic/Teaching/David%20Copperfields%20Orient%20Express%20Card%20Trick.pdf
# manually making the data frame, haha
d26_data <- data.frame(
  x_coord = c(1, 2, 3, 1, 2, 3, 1, 2, 3),
  y_coord = c(1, 1, 1, 2, 2, 2, 3, 3, 3),
  building = c("Biomedical Sciences\nand Physics", "Yablokoff-Wallace\nDining Center", "Administration", "Leo and Dottie\nKolligian Library", "Arts and\nComputational Sciences", "Science and\nEngineering 1", "Sustainability Research\nand Engineering", "Classroom and\nOffice Building 1", "Social Science\nand Management")
)
```

```{r}
# baseplot
d26_data |>
  # filter(building %in% c("Biomedical Sciences\nand Physics", "Yablokoff-Wallace\nDining Center", "Administration", "Leo and Dottie\nKolligian Library", "Arts and\nComputational Sciences", "Science and\nEngineering 1", "Sustainability Research\nand Engineering", "Classroom and\nOffice Building 1", "Social Science\nand Management")) |>
  ggplot(aes(x = x_coord, y = y_coord, label = building)) +
  geom_tile(fill = "#FFBF3C", color = "#002856") + #UC Merced brand colors
  ggfittext::geom_fit_text(color = "#002856", grow = TRUE) +
  labs(title = "UC Merced",
       subtitle = "Hide-and-Seek",
       caption = "Moves may be up, down, left,\nor right (not diagonally)",
       x = "",
       y = "") +
  theme(axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks = element_blank(),
        legend.position = "none",
        legend.title = element_blank(),
        panel.background = element_rect(fill = "#002856"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        plot.title = element_text(color = "#DAA900", face = "bold",
                                  hjust = 0.5, size = 30),
        plot.subtitle = element_text(color = "#F18A00", face = "bold",
                                  hjust = 0.5, size = 25),
        plot.caption = element_text(color = "#64A43A", face = "bold",
                                  hjust = 0.5, size = 20))
```

```{r}
# start
p1 <- d26_data |>
  filter(building %in% c("Yablokoff-Wallace\nDining Center", "Leo and Dottie\nKolligian Library", "Science and\nEngineering 1", "Classroom and\nOffice Building 1")) |>
  ggplot(aes(x = x_coord, y = y_coord, label = building)) +
  geom_tile(fill = "#FFBF3C", color = "#002856") + #UC Merced brand colors
  ggfittext::geom_fit_text(color = "#002856", grow = TRUE) +
  labs(title = "Let's play a game of\nHide-and-Seek!\nChoose a starting location:",
       subtitle = "",
       caption = "",
       x = "",
       y = "") +
  theme(axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks = element_blank(),
        legend.position = "none",
        legend.title = element_blank(),
        panel.background = element_rect(fill = "#002856"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        plot.title = element_text(color = "#DAA900", face = "bold",
                                  hjust = 0.5, size = 30),
        plot.subtitle = element_text(color = "#F18A00", face = "bold",
                                  hjust = 0.5, size = 25),
        plot.caption = element_text(color = "#64A43A", face = "bold",
                                  hjust = 0.5, size = 20))
```

```{r}
# infill
p2 <- d26_data |>
  # filter(building %in% c("Yablokoff-Wallace\nDining Center", "Leo and Dottie\nKolligian Library", "Science and\nEngineering 1", "Classroom and\nOffice Building 1")) |>
  ggplot(aes(x = x_coord, y = y_coord, label = building)) +
  geom_tile(fill = "#FFBF3C", color = "#002856") + #UC Merced brand colors
  ggfittext::geom_fit_text(color = "#002856", grow = TRUE) +
  labs(title = "",
       subtitle = "Many more buildings have appeared",
       caption = "",
       x = "",
       y = "") +
  theme(axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks = element_blank(),
        legend.position = "none",
        legend.title = element_blank(),
        panel.background = element_rect(fill = "#002856"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        plot.title = element_text(color = "#DAA900", face = "bold",
                                  hjust = 0.5, size = 30),
        plot.subtitle = element_text(color = "#F18A00", face = "bold",
                                  hjust = 0.5, size = 25),
        plot.caption = element_text(color = "#64A43A", face = "bold",
                                  hjust = 0.5, size = 20))
```

```{r}
p3 <- d26_data |>
  ggplot(aes(x = x_coord, y = y_coord, label = building)) +
  geom_tile(fill = "#FFBF3C", color = "#002856") + #UC Merced brand colors
  ggfittext::geom_fit_text(color = "#002856", grow = TRUE) +
  labs(title = "Make Four Moves",
       subtitle = "",
       caption = "Moves may be up, down, left,\nor right (not diagonally)",
       x = "",
       y = "") +
  theme(axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks = element_blank(),
        legend.position = "none",
        legend.title = element_blank(),
        panel.background = element_rect(fill = "#002856"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        plot.title = element_text(color = "#DAA900", face = "bold",
                                  hjust = 0.5, size = 30),
        plot.subtitle = element_text(color = "#F18A00", face = "bold",
                                  hjust = 0.5, size = 25),
        plot.caption = element_text(color = "#64A43A", face = "bold",
                                  hjust = 0.5, size = 20))
```

```{r}
p4 <- d26_data |>
  ggplot(aes(x = x_coord, y = y_coord, label = building)) +
  geom_tile(fill = "#FFBF3C", color = "#002856") + #UC Merced brand colors
  ggfittext::geom_fit_text(color = "#002856", grow = TRUE) +
  labs(title = "",
       subtitle = "Now, I know that you're not\nin the Administration building",
       caption = "",
       x = "",
       y = "") +
  theme(axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks = element_blank(),
        legend.position = "none",
        legend.title = element_blank(),
        panel.background = element_rect(fill = "#002856"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        plot.title = element_text(color = "#DAA900", face = "bold",
                                  hjust = 0.5, size = 30),
        plot.subtitle = element_text(color = "#F18A00", face = "bold",
                                  hjust = 0.5, size = 25),
        plot.caption = element_text(color = "#64A43A", face = "bold",
                                  hjust = 0.5, size = 20))
```



```{r}
p5 <- d26_data |>
  filter(building %in% c("Biomedical Sciences\nand Physics", "Yablokoff-Wallace\nDining Center", "Leo and Dottie\nKolligian Library", "Arts and\nComputational Sciences", "Science and\nEngineering 1", "Sustainability Research\nand Engineering", "Classroom and\nOffice Building 1", "Social Science\nand Management")) |>
  ggplot(aes(x = x_coord, y = y_coord, label = building)) +
  geom_tile(fill = "#FFBF3C", color = "#002856") + #UC Merced brand colors
  ggfittext::geom_fit_text(color = "#002856", grow = TRUE) +
  labs(title = "Make Five Moves",
       subtitle = "",
       caption = "Moves may be up, down, left,\nor right (not diagonally)",
       x = "",
       y = "") +
  theme(axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks = element_blank(),
        legend.position = "none",
        legend.title = element_blank(),
        panel.background = element_rect(fill = "#002856"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        plot.title = element_text(color = "#DAA900", face = "bold",
                                  hjust = 0.5, size = 30),
        plot.subtitle = element_text(color = "#F18A00", face = "bold",
                                  hjust = 0.5, size = 25),
        plot.caption = element_text(color = "#64A43A", face = "bold",
                                  hjust = 0.5, size = 20))
```

```{r}
p6 <- d26_data |>
  filter(building %in% c("Biomedical Sciences\nand Physics", "Yablokoff-Wallace\nDining Center", "Leo and Dottie\nKolligian Library", "Arts and\nComputational Sciences", "Science and\nEngineering 1", "Sustainability Research\nand Engineering", "Classroom and\nOffice Building 1", "Social Science\nand Management")) |>
  ggplot(aes(x = x_coord, y = y_coord, label = building)) +
  geom_tile(fill = "#FFBF3C", color = "#002856") + #UC Merced brand colors
  ggfittext::geom_fit_text(color = "#002856", grow = TRUE) +
  labs(title = "",
       subtitle = "Since you are not in\nScience and Engineering,\nlet us remove that possibility",
       # caption = "Moves may be up, down, left,\nor right (not diagonally)",
       x = "",
       y = "") +
  theme(axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks = element_blank(),
        legend.position = "none",
        legend.title = element_blank(),
        panel.background = element_rect(fill = "#002856"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        plot.title = element_text(color = "#DAA900", face = "bold",
                                  hjust = 0.5, size = 30),
        plot.subtitle = element_text(color = "#F18A00", face = "bold",
                                  hjust = 0.5, size = 25),
        plot.caption = element_text(color = "#64A43A", face = "bold",
                                  hjust = 0.5, size = 20))
```

```{r}
p7 <- d26_data |>
  filter(building %in% c("Biomedical Sciences\nand Physics", "Yablokoff-Wallace\nDining Center", "Leo and Dottie\nKolligian Library", "Arts and\nComputational Sciences", "Sustainability Research\nand Engineering", "Classroom and\nOffice Building 1", "Social Science\nand Management")) |>
  ggplot(aes(x = x_coord, y = y_coord, label = building)) +
  geom_tile(fill = "#FFBF3C", color = "#002856") + #UC Merced brand colors
  ggfittext::geom_fit_text(color = "#002856", grow = TRUE) +
  labs(title = "Make Two Moves",
       # subtitle = "Since you are not in\nScience and Engineering,\nlet us remove that possibility",
       caption = "Moves may be up, down, left,\nor right (not diagonally)",
       x = "",
       y = "") +
  theme(axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks = element_blank(),
        legend.position = "none",
        legend.title = element_blank(),
        panel.background = element_rect(fill = "#002856"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        plot.title = element_text(color = "#DAA900", face = "bold",
                                  hjust = 0.5, size = 30),
        plot.subtitle = element_text(color = "#F18A00", face = "bold",
                                  hjust = 0.5, size = 25),
        plot.caption = element_text(color = "#64A43A", face = "bold",
                                  hjust = 0.5, size = 20))
```

```{r}
p8 <- d26_data |>
  filter(building %in% c("Biomedical Sciences\nand Physics", "Yablokoff-Wallace\nDining Center", "Leo and Dottie\nKolligian Library", "Arts and\nComputational Sciences", "Sustainability Research\nand Engineering", "Classroom and\nOffice Building 1", "Social Science\nand Management")) |>
  ggplot(aes(x = x_coord, y = y_coord, label = building)) +
  geom_tile(fill = "#FFBF3C", color = "#002856") + #UC Merced brand colors
  ggfittext::geom_fit_text(color = "#002856", grow = TRUE) +
  labs(title = "",
       subtitle = "Since you are not in\nthe dining center,\nwe remove that from the diagram",
       # caption = "Moves may be up, down, left,\nor right (not diagonally)",
       x = "",
       y = "") +
  theme(axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks = element_blank(),
        legend.position = "none",
        legend.title = element_blank(),
        panel.background = element_rect(fill = "#002856"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        plot.title = element_text(color = "#DAA900", face = "bold",
                                  hjust = 0.5, size = 30),
        plot.subtitle = element_text(color = "#F18A00", face = "bold",
                                  hjust = 0.5, size = 25),
        plot.caption = element_text(color = "#64A43A", face = "bold",
                                  hjust = 0.5, size = 20))
```

```{r}
p9 <- d26_data |>
  filter(building %in% c("Biomedical Sciences\nand Physics", "Leo and Dottie\nKolligian Library", "Arts and\nComputational Sciences", "Sustainability Research\nand Engineering", "Classroom and\nOffice Building 1", "Social Science\nand Management")) |>
  ggplot(aes(x = x_coord, y = y_coord, label = building)) +
  geom_tile(fill = "#FFBF3C", color = "#002856") + #UC Merced brand colors
  ggfittext::geom_fit_text(color = "#002856", grow = TRUE) +
  labs(title = "Make Three Moves",
       # subtitle = "Since you are not in\nthe dining center,\nwe remove that from the diagram",
       caption = "Moves may be up, down, left,\nor right (not diagonally)",
       x = "",
       y = "") +
  theme(axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks = element_blank(),
        legend.position = "none",
        legend.title = element_blank(),
        panel.background = element_rect(fill = "#002856"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        plot.title = element_text(color = "#DAA900", face = "bold",
                                  hjust = 0.5, size = 30),
        plot.subtitle = element_text(color = "#F18A00", face = "bold",
                                  hjust = 0.5, size = 25),
        plot.caption = element_text(color = "#64A43A", face = "bold",
                                  hjust = 0.5, size = 20))
```

```{r}
p10 <- d26_data |>
  filter(building %in% c("Biomedical Sciences\nand Physics", "Leo and Dottie\nKolligian Library", "Arts and\nComputational Sciences", "Sustainability Research\nand Engineering", "Classroom and\nOffice Building 1", "Social Science\nand Management")) |>
  ggplot(aes(x = x_coord, y = y_coord, label = building)) +
  geom_tile(fill = "#FFBF3C", color = "#002856") + #UC Merced brand colors
  ggfittext::geom_fit_text(color = "#002856", grow = TRUE) +
  labs(title = " ",
       subtitle = "At this point, you are\nnot in SSM nor BSP",
       # caption = "Moves may be up, down, left,\nor right (not diagonally)",
       x = "",
       y = "") +
  theme(axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks = element_blank(),
        legend.position = "none",
        legend.title = element_blank(),
        panel.background = element_rect(fill = "#002856"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        plot.title = element_text(color = "#DAA900", face = "bold",
                                  hjust = 0.5, size = 30),
        plot.subtitle = element_text(color = "#F18A00", face = "bold",
                                  hjust = 0.5, size = 25),
        plot.caption = element_text(color = "#64A43A", face = "bold",
                                  hjust = 0.5, size = 20))
```

```{r}
p11 <- d26_data |>
  filter(building %in% c("Leo and Dottie\nKolligian Library", "Arts and\nComputational Sciences", "Sustainability Research\nand Engineering", "Classroom and\nOffice Building 1")) |>
  ggplot(aes(x = x_coord, y = y_coord, label = building)) +
  geom_tile(fill = "#FFBF3C", color = "#002856") + #UC Merced brand colors
  ggfittext::geom_fit_text(color = "#002856", grow = TRUE) +
  labs(title = "Make Three Moves",
       # subtitle = "At this point, you are\nnot in SSM nor BSP",
       caption = "Moves may be up, down, left,\nor right (not diagonally)",
       x = "",
       y = "") +
  theme(axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks = element_blank(),
        legend.position = "none",
        legend.title = element_blank(),
        panel.background = element_rect(fill = "#002856"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        plot.title = element_text(color = "#DAA900", face = "bold",
                                  hjust = 0.5, size = 30),
        plot.subtitle = element_text(color = "#F18A00", face = "bold",
                                  hjust = 0.5, size = 25),
        plot.caption = element_text(color = "#64A43A", face = "bold",
                                  hjust = 0.5, size = 20))
```

```{r}
p12 <- d26_data |>
  filter(building %in% c("Leo and Dottie\nKolligian Library", "Arts and\nComputational Sciences", "Sustainability Research\nand Engineering", "Classroom and\nOffice Building 1")) |>
  ggplot(aes(x = x_coord, y = y_coord, label = building)) +
  geom_tile(fill = "#FFBF3C", color = "#002856") + #UC Merced brand colors
  ggfittext::geom_fit_text(color = "#002856", grow = TRUE) +
  labs(title = " ",
       subtitle = "Even though you did visit\nClassroom and Office Building 1 ,\nyou are not there now.",
       # caption = "Moves may be up, down, left,\nor right (not diagonally)",
       x = "",
       y = "") +
  theme(axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks = element_blank(),
        legend.position = "none",
        legend.title = element_blank(),
        panel.background = element_rect(fill = "#002856"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        plot.title = element_text(color = "#DAA900", face = "bold",
                                  hjust = 0.5, size = 30),
        plot.subtitle = element_text(color = "#F18A00", face = "bold",
                                  hjust = 0.5, size = 25),
        plot.caption = element_text(color = "#64A43A", face = "bold",
                                  hjust = 0.5, size = 20))
```

```{r}
p13 <- d26_data |>
  filter(building %in% c("Leo and Dottie\nKolligian Library", "Arts and\nComputational Sciences", "Sustainability Research\nand Engineering")) |>
  ggplot(aes(x = x_coord, y = y_coord, label = building)) +
  geom_tile(fill = "#FFBF3C", color = "#002856") + #UC Merced brand colors
  ggfittext::geom_fit_text(color = "#002856", grow = TRUE) +
  labs(title = "Make One Last Move",
       # subtitle = "Even though you did visit\nClassroom and Office Building 1 ,\nyou are not there now.",
       caption = "Moves may be up, down, left,\nor right (not diagonally)",
       x = "",
       y = "") +
  theme(axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks = element_blank(),
        legend.position = "none",
        legend.title = element_blank(),
        panel.background = element_rect(fill = "#002856"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        plot.title = element_text(color = "#DAA900", face = "bold",
                                  hjust = 0.5, size = 30),
        plot.subtitle = element_text(color = "#F18A00", face = "bold",
                                  hjust = 0.5, size = 25),
        plot.caption = element_text(color = "#64A43A", face = "bold",
                                  hjust = 0.5, size = 20))
```
```{r}
p14 <- d26_data |>
  filter(building %in% c("Leo and Dottie\nKolligian Library")) |>
  ggplot(aes(x = x_coord, y = y_coord, label = building)) +
  geom_tile(fill = "#FFBF3C", color = "#002856") + #UC Merced brand colors
  ggfittext::geom_fit_text(color = "#002856", grow = TRUE) +
  labs(title = "",
       subtitle = "I have found you\nin the library!",
       caption = "Thanks for playing!",
       x = "",
       y = "") +
  theme(axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks = element_blank(),
        legend.position = "none",
        legend.title = element_blank(),
        panel.background = element_rect(fill = "#002856"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        plot.title = element_text(color = "#DAA900", face = "bold",
                                  hjust = 0.5, size = 30),
        plot.subtitle = element_text(color = "#F18A00", face = "bold",
                                  hjust = 0.5, size = 25),
        plot.caption = element_text(color = "#64A43A", face = "bold",
                                  hjust = 0.5, size = 20))
```
```{r}
ggsave("day26_plot1.jpg", p1, width = 8, height = 6, units = "in")
ggsave("day26_plot2.jpg", p2, width = 8, height = 6, units = "in")
ggsave("day26_plot3.jpg", p3, width = 8, height = 6, units = "in")
ggsave("day26_plot4.jpg", p4, width = 8, height = 6, units = "in")
ggsave("day26_plot5.jpg", p5, width = 8, height = 6, units = "in")
ggsave("day26_plot6.jpg", p6, width = 8, height = 6, units = "in")
ggsave("day26_plot7.jpg", p7, width = 8, height = 6, units = "in")
ggsave("day26_plot8.jpg", p8, width = 8, height = 6, units = "in")
ggsave("day26_plot9.jpg", p9, width = 8, height = 6, units = "in")
ggsave("day26_plot10.jpg", p10, width = 8, height = 6, units = "in")
ggsave("day26_plot11.jpg", p11, width = 8, height = 6, units = "in")
ggsave("day26_plot12.jpg", p12, width = 8, height = 6, units = "in")
ggsave("day26_plot13.jpg", p13, width = 8, height = 6, units = "in")
ggsave("day26_plot14.jpg", p14, width = 8, height = 6, units = "in")
```

Crummy use of alt text:

The initial set up was a 3-by-3 grid of rectangles that had 9 labels for UC Merced buildings.  I am not sure how best to explain the rest here in an alt text setting, but if you want more information, feel free to contact me.




